# --- Basic options --- #

# Name of website
title: Lycée Ravel Saint-Jean-de-Luz

# Short description of your site
description: Ressources de Mathématiques et des SNT (entre autres...)

# Your name to show in the footer
author: Yann Mobianov

# --- List of links in the navigation bar --- #

navbar-links:
  Accueil : index.html
  
  Seconde : 
    - Seconde 4 : https://github.com/ymobian/Ressources-Monsieur/tree/master/Seconde4
    - SNT: https://github.com/ymobian/Ressources-Monsieur/tree/master/SNT
   
  Première STMG  : https://github.com/ymobian/Ressources-Monsieur/tree/master/Premiere
  
  Terminale :
    - Spécialité : https://github.com/ymobian/Ressources-Monsieur/tree/master/TMaths3.TMaths6
    - Expertes :  https://github.com/ymobian/Ressources-Monsieur/tree/master/Maths.Expertes
    - Grand oral : https://www.education.gouv.fr/bo/20/Special2/MENE2002780N.htm?cid_bo=149115
    - Ens. scientifique : https://github.com/ymobian/Ressources-Monsieur/tree/master/Enseignement.Scientifique
  
  Parcoursup : 
    - Le site : https://www.parcoursup.fr/
    - Les data : https://data.enseignementsup-recherche.gouv.fr/pages/parcoursupdata/?disjunctive.fili
    - Le calendrier : https://cache.media.enseignementsup-recherche.gouv.fr/file/Mediatheque/02/5/infographie_calendrier_1420025.pdf
    - L'Onisep : https://www.terminales2021-2022.fr/
    
  Pronote : 
  


# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/fluide.png"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image






# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email : maiaboo64@gmail.com
  github: matharavel
  youtube: channel/UCf20K2AUAZH8x6Q1Z2KnYXg?view_as=subscriber
  twitter: 
  
  #rss: 
  #email :
  
  
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
# snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
  spotify: mana
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
 yelp: yourname
#  telegram: yourname
#  calendly: yourname

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: 
  facebook: 
  linkedin: 

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "ymobian.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository", "branch", and "endpoint".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#  reCaptcha:
#    siteKey  : # Use your own site key, you need to apply for one on Google
#    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
